export type SkillTaxonomyNode = {
  id: string;
  name: string;
  category: string;
  aliases: string[];
};

const nodes = [
  ["javascript", "JavaScript", "Web Engineering", ["js", "ecmascript"]],
  ["typescript", "TypeScript", "Web Engineering", ["ts", "typed javascript"]],
  ["html", "HTML", "Web Engineering", ["html5", "semantic html"]],
  ["css", "CSS", "Web Engineering", ["css3", "responsive css"]],
  ["react", "React", "Frontend Engineering", ["reactjs", "react.js"]],
  ["nextjs", "Next.js", "Frontend Engineering", ["nextjs", "next js"]],
  ["vite", "Vite", "Frontend Tooling", ["vitejs"]],
  ["tailwind-css", "Tailwind CSS", "Frontend Engineering", ["tailwind"]],
  ["responsive-design", "Responsive Web Design", "Frontend Engineering", ["responsive design"]],
  ["ui-component-development", "UI Component Development", "Frontend Engineering", ["component library", "ui components"]],
  ["frontend-development", "Frontend Development", "Frontend Engineering", ["web frontend"]],
  ["nodejs", "Node.js", "Backend Engineering", ["node", "node js"]],
  ["expressjs", "Express.js", "Backend Engineering", ["express"]],
  ["fastapi", "FastAPI", "Backend Engineering", ["python fastapi"]],
  ["flask", "Flask", "Backend Engineering", ["flask framework"]],
  ["django", "Django", "Backend Engineering", ["django framework"]],
  ["rest-api-development", "REST API Development", "Backend Engineering", ["rest api", "api development"]],
  ["websocket-development", "WebSocket Development", "Backend Engineering", ["websockets", "real-time api"]],
  ["full-stack-development", "Full-Stack Development", "Software Engineering", ["full stack", "fullstack"]],
  ["python", "Python", "Programming Languages", ["python3"]],
  ["csharp", "C#", "Programming Languages", ["c sharp", ".net c#"]],
  ["cplusplus", "C++", "Programming Languages", ["cpp", "c plus plus"]],
  ["java", "Java", "Programming Languages", []],
  ["kotlin", "Kotlin", "Programming Languages", []],
  ["dart", "Dart", "Programming Languages", []],
  ["go", "Go", "Programming Languages", ["golang"]],
  ["rust", "Rust", "Programming Languages", []],
  ["flutter", "Flutter", "Mobile Development", ["flutter framework"]],
  ["jetpack-compose", "Jetpack Compose", "Mobile Development", ["compose"]],
  ["android-development", "Android Development", "Mobile Development", ["android apps"]],
  ["ios-development", "iOS Development", "Mobile Development", ["swiftui", "ios apps"]],
  ["sql", "SQL", "Data and Databases", ["structured query language"]],
  ["postgresql", "PostgreSQL", "Data and Databases", ["postgres"]],
  ["mysql", "MySQL", "Data and Databases", []],
  ["sqlite", "SQLite", "Data and Databases", []],
  ["firebase", "Firebase", "Data and Databases", ["firestore", "firebase storage"]],
  ["supabase", "Supabase", "Data and Databases", []],
  ["database-design", "Database Design", "Data and Databases", ["data modeling", "schema design"]],
  ["data-analysis", "Data Analysis", "Data and Databases", ["analytics"]],
  ["data-modeling", "Data Modeling", "Data and Databases", []],
  ["pandas", "Pandas", "Data and Databases", []],
  ["numpy", "NumPy", "Data and Databases", []],
  ["machine-learning", "Machine Learning", "AI Engineering", ["ml"]],
  ["natural-language-processing", "Natural Language Processing", "AI Engineering", ["nlp"]],
  ["llm-application-development", "LLM Application Development", "AI Engineering", ["generative ai", "llm apps"]],
  ["langchain", "LangChain", "AI Engineering", []],
  ["langgraph", "LangGraph", "AI Engineering", []],
  ["rag", "Retrieval-Augmented Generation", "AI Engineering", ["rag"]],
  ["prompt-engineering", "Prompt Engineering", "AI Engineering", ["prompt design"]],
  ["ai-agent-development", "AI Agent Development", "AI Engineering", ["ai agents", "agentic ai"]],
  ["openai-api", "OpenAI API Integration", "AI Engineering", ["openai"]],
  ["gemini-api", "Gemini API Integration", "AI Engineering", ["google gemini"]],
  ["n8n", "n8n Workflow Automation", "Automation", ["n8n"]],
  ["git", "Git", "Software Engineering", ["version control"]],
  ["github", "GitHub", "Software Engineering", ["github repositories"]],
  ["github-actions", "GitHub Actions", "DevOps", ["github workflows"]],
  ["cicd", "CI/CD", "DevOps", ["continuous integration", "continuous deployment"]],
  ["docker", "Docker", "DevOps", ["containers", "containerization"]],
  ["deployment", "Application Deployment", "DevOps", ["web deployment"]],
  ["software-testing", "Software Testing", "Quality Engineering", ["testing"]],
  ["unit-testing", "Unit Testing", "Quality Engineering", ["unit tests"]],
  ["integration-testing", "Integration Testing", "Quality Engineering", ["integration tests"]],
  ["api-testing", "API Testing", "Quality Engineering", ["postman", "api qa"]],
  ["playwright", "Playwright", "Quality Engineering", ["playwright testing"]],
  ["selenium", "Selenium", "Quality Engineering", ["selenium webdriver"]],
  ["pytest", "Pytest", "Quality Engineering", ["python testing"]],
  ["vitest", "Vitest", "Quality Engineering", []],
  ["jest", "Jest", "Quality Engineering", []],
  ["debugging", "Debugging", "Software Engineering", ["troubleshooting"]],
  ["object-oriented-programming", "Object-Oriented Programming", "Software Engineering", ["oop"]],
  ["software-design-patterns", "Software Design Patterns", "Software Architecture", ["design patterns"]],
  ["command-pattern", "Command Pattern", "Software Architecture", []],
  ["composite-pattern", "Composite Pattern", "Software Architecture", []],
  ["decorator-pattern", "Decorator Pattern", "Software Architecture", []],
  ["observer-pattern", "Observer Pattern", "Software Architecture", []],
  ["state-pattern", "State Pattern", "Software Architecture", []],
  ["strategy-pattern", "Strategy Pattern", "Software Architecture", []],
  ["rule-engine-development", "Rule Engine Development", "Software Architecture", ["rules engine"]],
  ["application-architecture", "Application Architecture", "Software Architecture", ["software architecture"]],
  ["json-data-processing", "JSON Data Processing", "Software Engineering", ["json handling"]],
  ["file-processing", "File Processing", "Software Engineering", ["file upload", "document processing"]],
  ["pdf-processing", "PDF Processing", "Software Engineering", ["pdf extraction", "pdf parsing"]],
  ["cli-development", "Command-Line Interface Development", "Software Engineering", ["cli", "command line"]],
  ["technical-documentation", "Technical Documentation", "Communication", ["readme writing"]],
  ["cybersecurity", "Cybersecurity", "Security Engineering", ["information security"]],
  ["web-application-security", "Web Application Security", "Security Engineering", ["appsec"]],
  ["threat-detection", "Threat Detection", "Security Engineering", ["threat analysis"]],
  ["security-testing", "Security Testing", "Security Engineering", ["penetration testing"]],
  ["authentication", "Authentication", "Security Engineering", ["auth"]],
  ["authorization", "Authorization", "Security Engineering", ["access control"]],
  ["ocr", "Optical Character Recognition", "Applied Computing", ["ocr"]],
  ["real-time-systems", "Real-Time Systems", "Applied Computing", ["real-time features"]],
  ["accessibility", "Digital Accessibility", "Product Engineering", ["accessible design", "a11y"]],
  ["ux-design", "User Experience Design", "Product Engineering", ["ux"]],
  ["product-design", "Product Design", "Product Engineering", ["product development"]],
  ["project-management", "Project Management", "Professional Skills", ["project planning"]],
  ["team-collaboration", "Team Collaboration", "Professional Skills", ["teamwork"]],
  ["technical-communication", "Technical Communication", "Communication", ["technical writing"]],
  ["written-communication", "Written Communication", "Communication", ["professional writing", "writing skills"]],
  ["verbal-communication", "Verbal Communication", "Communication", ["oral communication", "speaking"]],
  ["public-speaking", "Public Speaking", "Communication", ["presentations", "speech delivery"]],
  ["presentation-design", "Presentation Design", "Communication", ["slide design", "powerpoint"]],
  ["storytelling", "Storytelling", "Communication", ["narrative communication"]],
  ["active-listening", "Active Listening", "Communication", ["listening skills"]],
  ["interviewing", "Interviewing", "Communication", ["conducting interviews"]],
  ["negotiation", "Negotiation", "Communication", ["negotiating"]],
  ["conflict-resolution", "Conflict Resolution", "Communication", ["mediation"]],
  ["cross-cultural-communication", "Cross-Cultural Communication", "Communication", ["intercultural communication"]],
  ["english-language", "English Language Proficiency", "Languages", ["english"]],
  ["mandarin-language", "Mandarin Chinese", "Languages", ["chinese", "mandarin"]],
  ["malay-language", "Malay Language", "Languages", ["bahasa melayu", "malay"]],
  ["tamil-language", "Tamil Language", "Languages", ["tamil"]],
  ["translation", "Translation", "Languages", ["language translation"]],
  ["interpretation", "Language Interpretation", "Languages", ["interpreting"]],
  ["leadership", "Leadership", "Professional Skills", ["team leadership"]],
  ["time-management", "Time Management", "Professional Skills", ["scheduling", "prioritization"]],
  ["problem-solving", "Problem Solving", "Professional Skills", ["analytical problem solving"]],
  ["critical-thinking", "Critical Thinking", "Professional Skills", ["critical analysis"]],
  ["decision-making", "Decision Making", "Professional Skills", ["judgement"]],
  ["adaptability", "Adaptability", "Professional Skills", ["flexibility"]],
  ["creativity", "Creativity", "Professional Skills", ["creative thinking"]],
  ["attention-to-detail", "Attention to Detail", "Professional Skills", ["detail orientation"]],
  ["independent-learning", "Independent Learning", "Professional Skills", ["self-directed learning"]],
  ["mentoring", "Mentoring", "Professional Skills", ["peer mentoring"]],
  ["facilitation", "Facilitation", "Professional Skills", ["workshop facilitation"]],
  ["stakeholder-management", "Stakeholder Management", "Professional Skills", ["stakeholder engagement"]],
  ["event-planning", "Event Planning", "Professional Skills", ["event management"]],
  ["volunteer-coordination", "Volunteer Coordination", "Professional Skills", ["volunteer management"]],
  ["business-analysis", "Business Analysis", "Business and Management", ["requirements analysis"]],
  ["business-strategy", "Business Strategy", "Business and Management", ["strategic planning"]],
  ["business-modeling", "Business Model Development", "Business and Management", ["business model canvas"]],
  ["entrepreneurship", "Entrepreneurship", "Business and Management", ["startup development"]],
  ["operations-management", "Operations Management", "Business and Management", ["business operations"]],
  ["process-improvement", "Process Improvement", "Business and Management", ["continuous improvement"]],
  ["quality-management", "Quality Management", "Business and Management", ["quality assurance management"]],
  ["supply-chain-management", "Supply Chain Management", "Business and Management", ["supply chain"]],
  ["logistics-management", "Logistics Management", "Business and Management", ["logistics"]],
  ["inventory-management", "Inventory Management", "Business and Management", ["stock control"]],
  ["procurement", "Procurement", "Business and Management", ["purchasing"]],
  ["vendor-management", "Vendor Management", "Business and Management", ["supplier management"]],
  ["risk-management", "Risk Management", "Business and Management", ["risk assessment"]],
  ["change-management", "Change Management", "Business and Management", ["organizational change"]],
  ["human-resource-management", "Human Resource Management", "Human Resources", ["hr management"]],
  ["recruitment", "Recruitment", "Human Resources", ["talent acquisition", "hiring"]],
  ["employee-onboarding", "Employee Onboarding", "Human Resources", ["staff onboarding"]],
  ["training-development", "Training and Development", "Human Resources", ["learning and development"]],
  ["performance-management", "Performance Management", "Human Resources", ["employee performance"]],
  ["workforce-planning", "Workforce Planning", "Human Resources", ["manpower planning"]],
  ["marketing-strategy", "Marketing Strategy", "Marketing", ["marketing planning"]],
  ["digital-marketing", "Digital Marketing", "Marketing", ["online marketing"]],
  ["social-media-marketing", "Social Media Marketing", "Marketing", ["social media management"]],
  ["content-marketing", "Content Marketing", "Marketing", ["content strategy"]],
  ["search-engine-optimization", "Search Engine Optimization", "Marketing", ["seo"]],
  ["search-engine-marketing", "Search Engine Marketing", "Marketing", ["sem", "paid search"]],
  ["email-marketing", "Email Marketing", "Marketing", ["email campaigns"]],
  ["market-research", "Market Research", "Marketing", ["consumer research"]],
  ["consumer-behavior", "Consumer Behavior Analysis", "Marketing", ["customer behavior"]],
  ["brand-management", "Brand Management", "Marketing", ["branding"]],
  ["campaign-management", "Marketing Campaign Management", "Marketing", ["campaign planning"]],
  ["copywriting", "Copywriting", "Marketing", ["advertising copy"]],
  ["sales", "Sales", "Sales and Customer Service", ["selling"]],
  ["sales-prospecting", "Sales Prospecting", "Sales and Customer Service", ["lead generation"]],
  ["account-management", "Account Management", "Sales and Customer Service", ["client accounts"]],
  ["customer-service", "Customer Service", "Sales and Customer Service", ["customer support"]],
  ["customer-relationship-management", "Customer Relationship Management", "Sales and Customer Service", ["crm"]],
  ["customer-needs-analysis", "Customer Needs Analysis", "Sales and Customer Service", ["needs assessment"]],
  ["complaint-resolution", "Customer Complaint Resolution", "Sales and Customer Service", ["service recovery"]],
  ["retail-operations", "Retail Operations", "Sales and Customer Service", ["retail management"]],
  ["merchandising", "Merchandising", "Sales and Customer Service", ["visual merchandising"]],
  ["financial-accounting", "Financial Accounting", "Finance and Accounting", ["accounting"]],
  ["management-accounting", "Management Accounting", "Finance and Accounting", ["cost accounting"]],
  ["bookkeeping", "Bookkeeping", "Finance and Accounting", ["ledger management"]],
  ["financial-analysis", "Financial Analysis", "Finance and Accounting", ["finance analysis"]],
  ["financial-modeling", "Financial Modeling", "Finance and Accounting", ["financial models"]],
  ["budgeting", "Budgeting", "Finance and Accounting", ["budget planning"]],
  ["forecasting", "Financial Forecasting", "Finance and Accounting", ["financial projections"]],
  ["cash-flow-management", "Cash Flow Management", "Finance and Accounting", ["cash flow"]],
  ["investment-analysis", "Investment Analysis", "Finance and Accounting", ["equity analysis"]],
  ["portfolio-management-finance", "Investment Portfolio Management", "Finance and Accounting", ["asset management"]],
  ["corporate-finance", "Corporate Finance", "Finance and Accounting", ["business finance"]],
  ["taxation", "Taxation", "Finance and Accounting", ["tax accounting"]],
  ["auditing", "Auditing", "Finance and Accounting", ["financial audit"]],
  ["internal-controls", "Internal Controls", "Finance and Accounting", ["financial controls"]],
  ["banking-operations", "Banking Operations", "Finance and Accounting", ["banking"]],
  ["credit-analysis", "Credit Analysis", "Finance and Accounting", ["credit risk"]],
  ["insurance-operations", "Insurance Operations", "Finance and Accounting", ["insurance"]],
  ["anti-money-laundering", "Anti-Money Laundering", "Finance and Accounting", ["aml"]],
  ["know-your-customer", "Know Your Customer Compliance", "Finance and Accounting", ["kyc"]],
  ["economics-analysis", "Economic Analysis", "Economics", ["economics"]],
  ["microeconomics", "Microeconomics", "Economics", []],
  ["macroeconomics", "Macroeconomics", "Economics", []],
  ["econometrics", "Econometrics", "Economics", ["economic modeling"]],
  ["policy-analysis", "Policy Analysis", "Public Policy", ["public policy analysis"]],
  ["public-administration", "Public Administration", "Public Policy", ["government administration"]],
  ["program-evaluation", "Program Evaluation", "Public Policy", ["programme evaluation"]],
  ["community-engagement", "Community Engagement", "Public Policy", ["public engagement"]],
  ["legal-research", "Legal Research", "Law and Legal Services", ["case law research"]],
  ["legal-writing", "Legal Writing", "Law and Legal Services", ["legal drafting"]],
  ["contract-drafting", "Contract Drafting", "Law and Legal Services", ["contracts"]],
  ["contract-review", "Contract Review", "Law and Legal Services", ["agreement review"]],
  ["case-analysis", "Legal Case Analysis", "Law and Legal Services", ["case briefing"]],
  ["regulatory-compliance", "Regulatory Compliance", "Law and Legal Services", ["compliance"]],
  ["data-privacy", "Data Privacy", "Law and Legal Services", ["privacy law", "pdpa", "gdpr"]],
  ["intellectual-property", "Intellectual Property", "Law and Legal Services", ["ip law"]],
  ["dispute-resolution", "Dispute Resolution", "Law and Legal Services", ["alternative dispute resolution"]],
  ["paralegal-support", "Paralegal Support", "Law and Legal Services", ["legal administration"]],
  ["research-design", "Research Design", "Research", ["study design"]],
  ["literature-review", "Literature Review", "Research", ["academic literature review"]],
  ["qualitative-research", "Qualitative Research", "Research", ["qualitative methods"]],
  ["quantitative-research", "Quantitative Research", "Research", ["quantitative methods"]],
  ["mixed-methods-research", "Mixed Methods Research", "Research", ["mixed methods"]],
  ["survey-design", "Survey Design", "Research", ["questionnaire design"]],
  ["experimental-design", "Experimental Design", "Research", ["experiments"]],
  ["data-collection", "Data Collection", "Research", ["research data collection"]],
  ["statistical-analysis", "Statistical Analysis", "Research", ["statistics"]],
  ["hypothesis-testing", "Hypothesis Testing", "Research", ["statistical testing"]],
  ["research-ethics", "Research Ethics", "Research", ["ethical research"]],
  ["academic-writing", "Academic Writing", "Research", ["research writing"]],
  ["citation-management", "Citation Management", "Research", ["references", "bibliography"]],
  ["laboratory-safety", "Laboratory Safety", "Laboratory Science", ["lab safety"]],
  ["laboratory-techniques", "Laboratory Techniques", "Laboratory Science", ["lab skills"]],
  ["sample-preparation", "Sample Preparation", "Laboratory Science", ["specimen preparation"]],
  ["microscopy", "Microscopy", "Laboratory Science", ["microscope use"]],
  ["spectroscopy", "Spectroscopy", "Laboratory Science", []],
  ["chromatography", "Chromatography", "Laboratory Science", []],
  ["titration", "Titration", "Laboratory Science", []],
  ["cell-culture", "Cell Culture", "Laboratory Science", ["tissue culture"]],
  ["pcr", "Polymerase Chain Reaction", "Laboratory Science", ["pcr"]],
  ["gel-electrophoresis", "Gel Electrophoresis", "Laboratory Science", []],
  ["chemical-analysis", "Chemical Analysis", "Laboratory Science", ["analytical chemistry"]],
  ["quality-control-laboratory", "Laboratory Quality Control", "Laboratory Science", ["lab qc"]],
  ["biology", "Biology", "Natural Sciences", ["biological science"]],
  ["molecular-biology", "Molecular Biology", "Natural Sciences", []],
  ["microbiology", "Microbiology", "Natural Sciences", []],
  ["genetics", "Genetics", "Natural Sciences", []],
  ["biochemistry", "Biochemistry", "Natural Sciences", []],
  ["chemistry", "Chemistry", "Natural Sciences", ["chemical science"]],
  ["organic-chemistry", "Organic Chemistry", "Natural Sciences", []],
  ["inorganic-chemistry", "Inorganic Chemistry", "Natural Sciences", []],
  ["physics", "Physics", "Natural Sciences", []],
  ["mechanics-physics", "Classical Mechanics", "Natural Sciences", []],
  ["thermodynamics", "Thermodynamics", "Natural Sciences", []],
  ["electromagnetism", "Electromagnetism", "Natural Sciences", []],
  ["environmental-science", "Environmental Science", "Natural Sciences", ["environment studies"]],
  ["ecology", "Ecology", "Natural Sciences", []],
  ["geology", "Geology", "Natural Sciences", ["earth science"]],
  ["geographic-information-systems", "Geographic Information Systems", "Geospatial", ["gis"]],
  ["spatial-analysis", "Spatial Analysis", "Geospatial", ["geospatial analysis"]],
  ["cartography", "Cartography", "Geospatial", ["map making"]],
  ["remote-sensing", "Remote Sensing", "Geospatial", []],
  ["mathematics", "Mathematics", "Mathematics", ["math"]],
  ["calculus", "Calculus", "Mathematics", []],
  ["linear-algebra", "Linear Algebra", "Mathematics", []],
  ["discrete-mathematics", "Discrete Mathematics", "Mathematics", []],
  ["probability", "Probability", "Mathematics", []],
  ["mathematical-modeling", "Mathematical Modeling", "Mathematics", ["mathematical modelling"]],
  ["numerical-methods", "Numerical Methods", "Mathematics", []],
  ["mechanical-design", "Mechanical Design", "Mechanical Engineering", ["machine design"]],
  ["computer-aided-design", "Computer-Aided Design", "Engineering Design", ["cad"]],
  ["solidworks", "SolidWorks", "Engineering Design", []],
  ["autocad", "AutoCAD", "Engineering Design", []],
  ["engineering-drawing", "Engineering Drawing", "Engineering Design", ["technical drawing"]],
  ["prototyping", "Prototyping", "Engineering Design", ["prototype development"]],
  ["rapid-prototyping", "Rapid Prototyping", "Engineering Design", ["3d printing"]],
  ["manufacturing-processes", "Manufacturing Processes", "Manufacturing", ["manufacturing"]],
  ["cnc-machining", "CNC Machining", "Manufacturing", ["cnc"]],
  ["lean-manufacturing", "Lean Manufacturing", "Manufacturing", ["lean"]],
  ["six-sigma", "Six Sigma", "Manufacturing", []],
  ["quality-control-manufacturing", "Manufacturing Quality Control", "Manufacturing", ["manufacturing qc"]],
  ["maintenance-planning", "Maintenance Planning", "Manufacturing", ["preventive maintenance"]],
  ["electrical-circuits", "Electrical Circuits", "Electrical Engineering", ["circuit analysis"]],
  ["electronics", "Electronics", "Electrical Engineering", ["electronic systems"]],
  ["pcb-design", "PCB Design", "Electrical Engineering", ["printed circuit boards"]],
  ["embedded-systems", "Embedded Systems", "Electrical Engineering", ["microcontrollers"]],
  ["arduino", "Arduino", "Electrical Engineering", []],
  ["raspberry-pi", "Raspberry Pi", "Electrical Engineering", []],
  ["plc-programming", "PLC Programming", "Electrical Engineering", ["programmable logic controllers"]],
  ["control-systems", "Control Systems", "Electrical Engineering", ["automation control"]],
  ["signal-processing", "Signal Processing", "Electrical Engineering", ["dsp"]],
  ["power-systems", "Electrical Power Systems", "Electrical Engineering", ["power engineering"]],
  ["civil-engineering-design", "Civil Engineering Design", "Civil Engineering", ["civil design"]],
  ["structural-analysis", "Structural Analysis", "Civil Engineering", ["structural engineering"]],
  ["construction-management", "Construction Management", "Civil Engineering", ["construction planning"]],
  ["quantity-surveying", "Quantity Surveying", "Civil Engineering", ["cost estimation construction"]],
  ["building-information-modeling", "Building Information Modeling", "Civil Engineering", ["bim"]],
  ["surveying", "Land Surveying", "Civil Engineering", ["geomatics"]],
  ["transportation-planning", "Transportation Planning", "Civil Engineering", ["transport planning"]],
  ["water-resources-engineering", "Water Resources Engineering", "Civil Engineering", ["hydrology"]],
  ["architecture-design", "Architectural Design", "Architecture", ["architecture"]],
  ["space-planning", "Space Planning", "Architecture", ["spatial planning"]],
  ["urban-planning", "Urban Planning", "Architecture", ["town planning"]],
  ["sustainable-design", "Sustainable Design", "Architecture", ["green design"]],
  ["nursing-care", "Nursing Care", "Healthcare", ["patient nursing"]],
  ["patient-assessment", "Patient Assessment", "Healthcare", ["clinical assessment"]],
  ["vital-sign-monitoring", "Vital Signs Monitoring", "Healthcare", ["vital signs"]],
  ["clinical-documentation", "Clinical Documentation", "Healthcare", ["medical documentation"]],
  ["infection-control", "Infection Prevention and Control", "Healthcare", ["infection prevention"]],
  ["first-aid", "First Aid", "Healthcare", ["basic life support"]],
  ["medication-administration", "Medication Administration", "Healthcare", ["administering medication"]],
  ["health-education", "Health Education", "Healthcare", ["patient education"]],
  ["public-health", "Public Health", "Healthcare", ["population health"]],
  ["epidemiology", "Epidemiology", "Healthcare", []],
  ["health-promotion", "Health Promotion", "Healthcare", ["wellness promotion"]],
  ["medical-terminology", "Medical Terminology", "Healthcare", []],
  ["pharmacy-practice", "Pharmacy Practice", "Healthcare", ["pharmacy"]],
  ["nutrition-planning", "Nutrition Planning", "Healthcare", ["diet planning"]],
  ["counselling", "Counselling", "Psychology and Social Services", ["counseling"]],
  ["psychological-assessment", "Psychological Assessment", "Psychology and Social Services", ["psychometrics"]],
  ["behavioral-observation", "Behavioral Observation", "Psychology and Social Services", ["behavioural observation"]],
  ["case-management-social", "Social Services Case Management", "Psychology and Social Services", ["social work case management"]],
  ["community-outreach", "Community Outreach", "Psychology and Social Services", ["outreach"]],
  ["crisis-intervention", "Crisis Intervention", "Psychology and Social Services", ["crisis support"]],
  ["social-work-practice", "Social Work Practice", "Psychology and Social Services", ["social work"]],
  ["lesson-planning", "Lesson Planning", "Education", ["teaching plans"]],
  ["curriculum-development", "Curriculum Development", "Education", ["curriculum design"]],
  ["classroom-management", "Classroom Management", "Education", ["class management"]],
  ["instructional-design", "Instructional Design", "Education", ["learning design"]],
  ["student-assessment", "Student Assessment", "Education", ["learning assessment"]],
  ["differentiated-instruction", "Differentiated Instruction", "Education", ["adaptive teaching"]],
  ["special-education", "Special Education", "Education", ["learning support"]],
  ["early-childhood-education", "Early Childhood Education", "Education", ["preschool education"]],
  ["educational-technology", "Educational Technology", "Education", ["edtech"]],
  ["tutoring", "Tutoring", "Education", ["academic tutoring"]],
  ["graphic-design", "Graphic Design", "Creative and Visual Design", ["visual design"]],
  ["illustration", "Illustration", "Creative and Visual Design", ["digital illustration"]],
  ["typography", "Typography", "Creative and Visual Design", ["type design"]],
  ["layout-design", "Layout Design", "Creative and Visual Design", ["editorial layout"]],
  ["branding-design", "Brand Identity Design", "Creative and Visual Design", ["brand design"]],
  ["adobe-photoshop", "Adobe Photoshop", "Creative and Visual Design", ["photoshop"]],
  ["adobe-illustrator", "Adobe Illustrator", "Creative and Visual Design", ["illustrator"]],
  ["figma", "Figma", "Creative and Visual Design", ["figma design"]],
  ["photography", "Photography", "Media Production", ["photo production"]],
  ["photo-editing", "Photo Editing", "Media Production", ["image editing"]],
  ["videography", "Videography", "Media Production", ["video production"]],
  ["video-editing", "Video Editing", "Media Production", ["post production"]],
  ["audio-production", "Audio Production", "Media Production", ["sound production"]],
  ["animation", "Animation", "Media Production", ["motion graphics"]],
  ["three-dimensional-modeling", "3D Modeling", "Media Production", ["3d design"]],
  ["journalism", "Journalism", "Media and Journalism", ["news reporting"]],
  ["news-writing", "News Writing", "Media and Journalism", ["reporting"]],
  ["editorial-writing", "Editorial Writing", "Media and Journalism", ["editorial content"]],
  ["fact-checking", "Fact Checking", "Media and Journalism", ["source verification"]],
  ["media-research", "Media Research", "Media and Journalism", ["journalistic research"]],
  ["broadcast-production", "Broadcast Production", "Media and Journalism", ["broadcasting"]],
  ["public-relations", "Public Relations", "Media and Journalism", ["pr"]],
  ["media-relations", "Media Relations", "Media and Journalism", ["press relations"]],
  ["music-performance", "Music Performance", "Performing Arts", ["musicianship"]],
  ["music-theory", "Music Theory", "Performing Arts", []],
  ["music-composition", "Music Composition", "Performing Arts", ["composing"]],
  ["acting", "Acting", "Performing Arts", ["theatre performance"]],
  ["dance-performance", "Dance Performance", "Performing Arts", ["dance"]],
  ["stage-management", "Stage Management", "Performing Arts", ["theatre production"]],
  ["hospitality-service", "Hospitality Service", "Hospitality and Tourism", ["guest service"]],
  ["hotel-operations", "Hotel Operations", "Hospitality and Tourism", ["hotel management"]],
  ["front-office-operations", "Front Office Operations", "Hospitality and Tourism", ["hotel reception"]],
  ["food-and-beverage-service", "Food and Beverage Service", "Hospitality and Tourism", ["f&b service"]],
  ["food-safety", "Food Safety", "Hospitality and Tourism", ["haccp"]],
  ["culinary-arts", "Culinary Arts", "Hospitality and Tourism", ["cooking"]],
  ["menu-planning", "Menu Planning", "Hospitality and Tourism", ["menu design"]],
  ["tourism-management", "Tourism Management", "Hospitality and Tourism", ["tourism"]],
  ["travel-planning", "Travel Planning", "Hospitality and Tourism", ["itinerary planning"]],
  ["event-hospitality", "Hospitality Event Management", "Hospitality and Tourism", ["banquet operations"]],
  ["agronomy", "Agronomy", "Agriculture", ["crop science"]],
  ["crop-production", "Crop Production", "Agriculture", ["crop cultivation"]],
  ["horticulture", "Horticulture", "Agriculture", ["plant cultivation"]],
  ["soil-management", "Soil Management", "Agriculture", ["soil science"]],
  ["animal-husbandry", "Animal Husbandry", "Agriculture", ["livestock management"]],
  ["aquaculture", "Aquaculture", "Agriculture", ["fish farming"]],
  ["farm-management", "Farm Management", "Agriculture", ["agricultural management"]],
  ["sustainable-agriculture", "Sustainable Agriculture", "Agriculture", ["sustainable farming"]],
  ["carpentry", "Carpentry", "Skilled Trades", ["woodworking"]],
  ["welding", "Welding", "Skilled Trades", ["metal welding"]],
  ["electrical-installation", "Electrical Installation", "Skilled Trades", ["electrical wiring"]],
  ["plumbing", "Plumbing", "Skilled Trades", ["pipe fitting"]],
  ["hvac", "HVAC Systems", "Skilled Trades", ["air conditioning", "refrigeration"]],
  ["automotive-maintenance", "Automotive Maintenance", "Skilled Trades", ["vehicle servicing"]],
  ["machining", "Machining", "Skilled Trades", ["machine tools"]],
  ["workplace-safety", "Workplace Safety", "Safety and Compliance", ["occupational safety"]],
  ["hazard-identification", "Hazard Identification", "Safety and Compliance", ["hazard assessment"]],
  ["incident-reporting", "Incident Reporting", "Safety and Compliance", ["safety reporting"]],
  ["emergency-response", "Emergency Response", "Safety and Compliance", ["emergency preparedness"]],
  ["microsoft-excel", "Microsoft Excel", "Office Productivity", ["excel", "spreadsheets"]],
  ["microsoft-word", "Microsoft Word", "Office Productivity", ["word processing"]],
  ["microsoft-powerpoint", "Microsoft PowerPoint", "Office Productivity", ["powerpoint", "presentations"]],
  ["google-sheets", "Google Sheets", "Office Productivity", ["sheets"]],
  ["spreadsheet-analysis", "Spreadsheet Analysis", "Office Productivity", ["spreadsheet modeling"]],
  ["data-visualization", "Data Visualization", "Analytics", ["charts", "dashboards"]],
  ["dashboard-development", "Dashboard Development", "Analytics", ["business dashboards"]],
  ["power-bi", "Microsoft Power BI", "Analytics", ["powerbi"]],
  ["tableau", "Tableau", "Analytics", []],
  ["spss", "SPSS", "Analytics", []],
  ["r-programming", "R Programming", "Analytics", ["r language"]],
  ["sas", "SAS", "Analytics", []],
  ["sports-coaching", "Sports Coaching", "Sports and Fitness", ["athletic coaching"]],
  ["fitness-instruction", "Fitness Instruction", "Sports and Fitness", ["personal training"]],
  ["exercise-programming", "Exercise Program Design", "Sports and Fitness", ["workout planning"]],
  ["sports-performance-analysis", "Sports Performance Analysis", "Sports and Fitness", ["performance analysis"]],
  ["sports-event-management", "Sports Event Management", "Sports and Fitness", ["sport events"]],
  ["sports-nutrition", "Sports Nutrition", "Sports and Fitness", ["athlete nutrition"]],
  ["injury-prevention", "Sports Injury Prevention", "Sports and Fitness", ["injury prevention"]],
  ["fashion-design", "Fashion Design", "Fashion and Textiles", ["apparel design"]],
  ["garment-construction", "Garment Construction", "Fashion and Textiles", ["dressmaking", "sewing"]],
  ["pattern-making", "Pattern Making", "Fashion and Textiles", ["garment patterns"]],
  ["textile-design", "Textile Design", "Fashion and Textiles", ["fabric design"]],
  ["fashion-illustration", "Fashion Illustration", "Fashion and Textiles", []],
  ["fashion-merchandising", "Fashion Merchandising", "Fashion and Textiles", ["fashion retail"]],
  ["beauty-therapy", "Beauty Therapy", "Personal Services", ["beauty services"]],
  ["hair-styling", "Hair Styling", "Personal Services", ["hairdressing"]],
  ["makeup-artistry", "Makeup Artistry", "Personal Services", ["makeup"]],
  ["skin-care", "Skin Care", "Personal Services", ["facial treatment"]],
  ["library-services", "Library Services", "Library and Information Science", ["librarianship"]],
  ["cataloguing", "Library Cataloguing", "Library and Information Science", ["cataloging"]],
  ["information-literacy", "Information Literacy", "Library and Information Science", ["source literacy"]],
  ["records-management", "Records Management", "Library and Information Science", ["document records"]],
  ["archives-management", "Archives Management", "Library and Information Science", ["archival work"]],
  ["knowledge-management", "Knowledge Management", "Library and Information Science", ["organizational knowledge"]],
  ["pharmaceutical-science", "Pharmaceutical Science", "Pharmaceutical Sciences", ["pharmaceutics"]],
  ["drug-formulation", "Drug Formulation", "Pharmaceutical Sciences", ["formulation science"]],
  ["pharmacology", "Pharmacology", "Pharmaceutical Sciences", []],
  ["clinical-trials", "Clinical Trials", "Pharmaceutical Sciences", ["clinical research"]],
  ["good-manufacturing-practice", "Good Manufacturing Practice", "Pharmaceutical Sciences", ["gmp"]],
  ["pharmaceutical-quality-control", "Pharmaceutical Quality Control", "Pharmaceutical Sciences", ["pharma qc"]],
  ["dental-assisting", "Dental Assisting", "Dental Care", ["dental support"]],
  ["oral-health-education", "Oral Health Education", "Dental Care", ["dental education"]],
  ["dental-radiography", "Dental Radiography", "Dental Care", ["dental x-ray"]],
  ["dental-laboratory-techniques", "Dental Laboratory Techniques", "Dental Care", ["dental lab"]],
  ["veterinary-care", "Veterinary Care", "Veterinary and Animal Care", ["animal healthcare"]],
  ["animal-handling", "Animal Handling", "Veterinary and Animal Care", ["animal restraint"]],
  ["veterinary-assisting", "Veterinary Assisting", "Veterinary and Animal Care", ["vet support"]],
  ["animal-welfare", "Animal Welfare", "Veterinary and Animal Care", ["animal wellbeing"]],
  ["aviation-operations", "Aviation Operations", "Aviation", ["airport operations"]],
  ["flight-planning", "Flight Planning", "Aviation", ["aviation planning"]],
  ["aircraft-maintenance", "Aircraft Maintenance", "Aviation", ["aviation maintenance"]],
  ["aviation-safety", "Aviation Safety", "Aviation", ["flight safety"]],
  ["air-traffic-operations", "Air Traffic Operations", "Aviation", ["air traffic control"]],
  ["maritime-operations", "Maritime Operations", "Maritime", ["shipping operations"]],
  ["navigation-maritime", "Maritime Navigation", "Maritime", ["ship navigation"]],
  ["marine-engineering", "Marine Engineering", "Maritime", ["ship engineering"]],
  ["port-operations", "Port Operations", "Maritime", ["harbor operations"]],
  ["maritime-safety", "Maritime Safety", "Maritime", ["ship safety"]],
  ["real-estate-sales", "Real Estate Sales", "Real Estate", ["property sales"]],
  ["property-management", "Property Management", "Real Estate", ["estate management"]],
  ["property-valuation", "Property Valuation", "Real Estate", ["real estate appraisal"]],
  ["real-estate-market-analysis", "Real Estate Market Analysis", "Real Estate", ["property market research"]],
  ["facilities-management", "Facilities Management", "Real Estate", ["building operations"]],
  ["museum-education", "Museum Education", "Museums and Heritage", ["museum learning"]],
  ["collections-management", "Collections Management", "Museums and Heritage", ["museum collections"]],
  ["heritage-conservation", "Heritage Conservation", "Museums and Heritage", ["cultural heritage"]],
  ["curatorial-practice", "Curatorial Practice", "Museums and Heritage", ["curating"]],
  ["fundraising", "Fundraising", "Nonprofit Management", ["donor fundraising"]],
  ["grant-writing", "Grant Writing", "Nonprofit Management", ["grant applications"]],
  ["donor-management", "Donor Management", "Nonprofit Management", ["donor relations"]],
  ["nonprofit-program-management", "Nonprofit Program Management", "Nonprofit Management", ["charity program management"]],
] as const;

export const skillTaxonomy: SkillTaxonomyNode[] = nodes.map(([id, name, category, aliases]) => ({
  id,
  name,
  category,
  aliases: [...aliases],
}));

export const skillTaxonomyById = new Map(skillTaxonomy.map((node) => [node.id, node]));

export const skillTaxonomyGroups = Array.from(
  skillTaxonomy.reduce((groups, node) => {
    const categoryNodes = groups.get(node.category) ?? [];
    categoryNodes.push(node);
    groups.set(node.category, categoryNodes);
    return groups;
  }, new Map<string, SkillTaxonomyNode[]>()),
)
  .map(([category, categoryNodes]) => ({
    category,
    nodes: categoryNodes.sort((left, right) => left.name.localeCompare(right.name)),
  }))
  .sort((left, right) => left.category.localeCompare(right.category));

export function taxonomyPromptList() {
  return skillTaxonomy.map((node) => `${node.id} | ${node.name} | ${node.category}`).join("\n");
}

export function findTaxonomyNode(idOrName: string) {
  const normalized = idOrName.trim().toLowerCase();
  return skillTaxonomyById.get(normalized)
    ?? skillTaxonomy.find((node) => node.name.toLowerCase() === normalized || node.aliases.some((alias) => alias.toLowerCase() === normalized));
}
